services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo:8.0.0
    command: ["mongod", "--noauth"]
    ports:
      - 27017:27017 
    volumes:
      - /data/db
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

